### ISSUE TITLE
Feature request: Folder directory selection in the bookmark dial tab

### ISSUE THREAD

**Issue by ReaLadge** [sblask/webextension-bookmark-dial#101]
I'm liking the extension but one thing that isnt that much of an issue but just a ease of access thing, is to have the "select folder" menu inside the actual bookmark dial tab itself instead of clicking on the extension icon every time. Would be handy to have since there's no visible subfolders.

**Comment by sblask** [comment]
I am not interested in implementing this. Especially because whether I click on the page or on the icon doesn't make much difference.
