### ISSUE TITLE
Google Maps Thumbnail is Black

### ISSUE THREAD

**Issue by Anchoy** [sblask/webextension-bookmark-dial#12]
Hello. The thumbnail for Google Maps  looks right for a few seconds, then turns black. Any idea why this is happening?

I love this extension. I've been looking for something like this for a long time. Thanks!

**Comment by sblask** [comment]
No idea and I will not look into it at the moment. I am busy reimplementing as a webextension and the whole thumbnail generation will be different. If it's still an issue when I am done with that, we can look at it again. This issue can stay open until then.

**Comment by Anchoy** [comment]
Great. Thanks and keep up the great work. I've noticed at least one other site which had the same type of issue.

**Comment by sblask** [comment]
If you find other sites with problems, please post the here so I can use them to test the new version!

**Comment by Anchoy** [comment]
![thumbnails](https://user-images.githubusercontent.com/30701314/28945768-6d5ecc8e-786d-11e7-9da6-fc41d23fd44a.jpg)

Look at the last two thumbnails. The hyperlinks go to:

https://www.google.com/maps/@29.9797909,-90.1073938,15z

and

http://www.nolaba.org/

Thanks!

**Comment by sblask** [comment]
Please check out the latest beta: https://addons.mozilla.org/en-US/firefox/addon/bookmark-dial/versions/beta No problems with the pages you had issues with. Let me know what you think (a lot has changed).

**Comment by sblask** [comment]
I just released the new version. Please re-open or open a new issue if you have any problems with it.
