### ISSUE TITLE
Scale BG image to fit smaller size

### ISSUE THREAD

**Issue by CyberKiller40** [sblask/webextension-bookmark-dial#13]
Currently the background image can be scaled, but if it;s not the same proportions as the monitor, then you get black borders.

An improvement would be to scale it to fit the smaller width/height and cut the portions which would go out of the visible window. Like scaled and cut display in KDE wallpaper. If that is not possible then just scale to fit width.

**Comment by sblask** [comment]
I am working on a new version that will be compatible to Firefox 57 and later and I need to redo everything. So the question is, what options do you want? Auto, contain, cover (see https://www.w3schools.com/cssref/playit.asp?filename=playcss_background-size&preval=cover) ?

**Comment by CyberKiller40** [comment]
OK, so the current "fit" is 'contain' centered horizontally, and I'm talking about 'cover' centered vertically. It would be best to have both options available.

Thanks!

**Comment by sblask** [comment]
Please check out the latest beta: https://addons.mozilla.org/en-US/firefox/addon/bookmark-dial/versions/beta and let me know what you think (a lot has changed).

**Comment by CyberKiller40** [comment]
I tried the beta and it didn't work too good. It opened once, I set the bookmark directory (this worked), I tried to set the image (from disk), but it didn't load the image, and the addon stopped working at all.

**Comment by sblask** [comment]
Did you read the known issues? To set the image, you'll have to open the settings from extension page, the popup won't work. What do you mean by stopped working?

**Comment by CyberKiller40** [comment]
Actually no, I didn't have time then to check any details. I'll try again tomorrow, and by stopped working I mean just that - the plugin didn't load at all, I got the default firefox new tab page.

**Comment by CyberKiller40** [comment]
Actually no, I didn't have time then to check any details. I'll try again tomorrow, and by stopped working I mean just that - the plugin didn't load at all, I got the default firefox new tab page.

**Comment by sblask** [comment]
That's strange because it's out of my control. It's Firefox doing all the loading. Did you try a re-install?

**Comment by sblask** [comment]
I just released the new version. Please re-open or open a new issue if you have any problems with it.

**Comment by CyberKiller40** [comment]
Sorry I didn't manage to test this earlier, it works as intended in the new version. Thanks!
