### ISSUE TITLE
Set as home page feature request

### ISSUE THREAD

**Issue by fritzophrenic** [sblask/webextension-bookmark-dial#14]
I like to have bookmarks dial as home page as well as "new tab" page. Right now I can do that by copy-pasting the location bar when I open a new tab, it looks like "moz-extension://{some sort of hash}/content-scripts/bookmark-dial.html" which I assume will change on updates or between PCs (maybe I'm wrong?)

But the "known issues" in the readme include: "the location bar is not cleared when a new tab is opened - this should be fixed in Firefox 57" so I would like a feature to be able to set the home page to the bookmarks dial.

**Comment by sblask** [comment]
I tried the API that exists to change the homepage but the result was rather awkward. And then I realised I get the same effect and better when I enable "Show your windows and Tab from last time". So when I close the browser and then start it again I start off where I left and when I closed all tabs before closing, I start off with a new tab that shows Bookmark Dial. It's exactly what I want. Can you try that out and let me know what you think?

**Comment by fritzophrenic** [comment]
Sadly that doesn't meet my needs. I actually also use "show windows and tabs from last time" and mainly use the home button as a quick method to see my "speed dial" sites, abandoning the site I'm currently on.

**Comment by sblask** [comment]
Please check out version 2.0.4b from https://addons.mozilla.org/en-GB/firefox/addon/bookmark-dial/versions/beta and let me know how that works for you.

**Comment by sblask** [comment]
One week without update. I'll close this for now, but you can still comment if you have an update.
