### ISSUE TITLE
Thumbnails Empty with New Version

### ISSUE THREAD

**Issue by Anchoy** [sblask/webextension-bookmark-dial#15]
Glad to see a new version released! Unfortunately all of my thumbnails are coming up as blank/black rectangles. I've waited over an hour with a fast internet connection but no luck. Any ideas on what might be wrong?

**Comment by sblask** [comment]
Did you not get the update message? Thumbnails cannot be generated in the background anymore. You'll have to visit all the bookmarks and keep everyone open in the visible tab until the thumbnail has been captured (it only takes a bit, but if you close/switch the tab to quickly the thumbnail is not taken). I know it's annoying, but there is no other way. Please have a look at the README, especially the know issues.

**Comment by Anchoy** [comment]
Understood. I will do it. Thank you!

**Comment by Anchoy** [comment]
This seems like a problematic approach for:

- users with existing bookmark collections
- users with multiple computers. (Don't want to have to click every bookmark on every computer).

Old approach had these issues covered. Also, I'm still getting some pages that do not generate thumbnails.

Thank you!

**Comment by sblask** [comment]
This is not by choice, it's the only way. You also need to make sure that the final URL in the tab is the same as the bookmarked one.

**Comment by Anchoy** [comment]
Thanks--Adjusting the URL fixed the thumbnail. Did Mozilla force you to abandon the old implementation which auto-generated the thumbnails?

**Comment by sblask** [comment]
Yes, from Firefox 57, there will be only the webextension API left. I had to almost completely rewrite the extension. Similar extensions use external thumbnail providers which have other problems like privacy, network access and no way to get thumbnails for intranet pages or logged in pages. But I wanted to keep thumbnail generation on the machine. I had the same problems after switching to the new version. I too use several computers. After the first pain, it gets better. Especially because thumbnails for new bookmarks are immediately available (unless you add them manually in the bookmark view, but the best way is to use the star button or Ctrl-D to bookmark the current page). When you then switch to the other computer, you know exactly which ones are new...

**Comment by Anchoy** [comment]
OK. Thanks for the explanation. Too bad they forced it to work this way. I will continue to use your cool add-on.

Best

**Comment by Anchoy** [comment]
By the way, the following two URLs come up as pure white thumbnails, even when I confirm the links:

https://help.apple.com/logicpro/mac/10.3/index.html

https://musicboxvillage.com/

Just to let you know.

Anthony

**Comment by sblask** [comment]
I think it's because it's using Javascript rendering, so the website has already finished loading, but the Javascript takes a while to show the content. You can always use the button in the toolbar menu to create a thumbnail once the content is actually there.

**Comment by Anchoy** [comment]
I see. That's pretty cool and it works well.

Is there an easy way to make your software upload the good set (with manual snapshots) of thumbnails to the cloud and then share across other computers? That would be really handy.

**Comment by sblask** [comment]
I guess I could do a manual import/export. That would be relatively straight forward, but maybe not super useful?

Browser sync has storage space limitations unfortunately, so that's no good. I don't know where else I could sync to and I am also a bit afraid of feature creep.

**Comment by Anchoy** [comment]
Maybe I didn't explain clearly. I mean, when all of the thumbnails look correct on one computer, have the software automatically upload that set to the cloud. Then when you first set up thumbnails on another computer, you could sync the set from the first one.

I understand about feature creep, so please take my suggestion with a grain of salt! The goal would be to only need to customize/optimize the thumbnails once and also avoid having to "click through" to thumbnails on subsequent computers. Just a thought! I will use your product regardless.

Thanks.

**Comment by sblask** [comment]
I did understand what you mean, but there is no magic place in the cloud where I can just send stuff. Browser sync would have been an option if storage wouldn't be limited, but it is.

**Comment by Anchoy** [comment]
Understood. Thanks.

**Comment by Anchoy** [comment]
Hi Sebastian.

I’ve been enjoying your Bookmarks Dial add on for Firefox. One idea: Could you create a function to make the add-on automatically create all the thumbnails in any particular folder when you push the button for that function? That would be very useful in my opinion.

Thanks!

**Comment by sblask** [comment]
Simply not possible...

**Comment by Yensan** [comment]
@sblask 
I just want a icon, not a thumbnails, and bookmark folder in right/left side, just as Safari do!  I think safari's bookmark page design is very well.
Anchoy open this issuse, @sblask why you not just put icons on page at first time! Simple, tidy, usefull...

**Comment by sblask** [comment]
@Yensan I have no idea how Safari looks like, but if you like it so much, just use it? There is no way to just put the icons. Also, if you just want the icons, you can use your browsers bookmark manager...

**Comment by Yensan** [comment]
@sblask 
Firefox's bookmark manager is so unconvinient
I use Mac Air in after-hours, but must use Windows in work-time!
I think as a navigate page, Safari's bookmarks is very nice.
