### ISSUE TITLE
Doesn't work with local (file protocol) pages

### ISSUE THREAD

**Issue by fritzophrenic** [sblask/webextension-bookmark-dial#16]
I have a bookmark to a file on my machine, like file:///path/to/my/file.html. It shows up in my Bookmarks Dial page, and it gets a thumbnail when I load file, however clicking on the thumbnail in Bookmarks Dial does nothing at all.

**Comment by sblask** [comment]
Right, that's another limitation of the webextension API. It's like this for all file:// and other privileged URLs (See URL argument on https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create - even if I don't even use that particular URL, but normal links - but the Bookmark Dial page is "special" with regards to webextensions). Nothing I can do but update the known issues :-(

**Comment by sblask** [comment]
Actually, what I wrote is not entirely correct, it works in Chrome if you enable access to file:// URLs - Firefox does not have such a setting yet...
