### ISSUE TITLE
Loading slowed down by other addons

### ISSUE THREAD

**Issue by vertigo220** [sblask/webextension-bookmark-dial#21]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Waterfox
- [x] Firefox

### What is your operating system?

- [X] Windows

### Description (please include examples/screenshots where applicable)

First, let me state I have this same issue with QuickDial. Considering it's loading local data, I would expect the dialer page to load near instantaneously, especially considering my computer's specs, yet it takes a couple seconds. This is with only nine bookmarks, and only one of them has a thumbnail image set. My normal browser is Waterfox, so I tried in Firefox, which only has a few addons installed and none enabled, and it's _significantly_ faster. I disabled most of my addons in Waterfox and it got a lot faster, but still not quite as fast as in Firefox (perhaps due to having more tabs open in Waterfox?). Going through re-enabling them a few at a time didn't reveal any one addon that consistently made much difference on its own, but collectively they do seem to slow it down.

However, I'm not even convinced the addons are to blame. I disabled the background image, using just a solid color, and that made it very fast, similar to Firefox. Thinking maybe it was due to the image being on a platter drive (HDD), I moved it to my SSD, but that didn't make a noticeable difference. In fact, Waterfox, pulling the image from the SSD, was still slower than Firefox which was still using the one on the HDD. It seems to me that Waterfox, possibly due to the addons, is much slower at loading the image, but it doesn't seem like that should be the case. Obviously, the easy solution is to just use a plain background, and that's not a big deal, but it would be nice to be able to use an image without it slowing things down.

Also, as mentioned, Quick Dial suffers from the same problem, though it's a hair slower with the background image and, while it also speeds up without it, the improvement isn't quite as much, so it's still a noticeable delay. So both addons seem to have the same issue, but QD is affected a bit more, though oddly enough QD is slightly faster using the background with most addons disabled. Both are instant on the clean Firefox.

Edit: Since it appears to be a common issue between BD and QD, here's the link to the issue I created for QD about this: https://github.com/MatMoul/quickdial-webext/issues/81

**Comment by sblask** [comment]
Nothing that I can do about it. Maybe you should file a bug with Firefox. Suspected culprit: slow local storage (see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage) where the speed seems to be affected by number of extensions. Where the image is stored is not relevant as the Bookmark Dial page does not access the image directly (it's not allowed to) Everything goes through local storage. Did not try with Firefox, but I do not seem to have a slow down with Chromium and 20-ish extensions
