### ISSUE TITLE
Set as home page

### ISSUE THREAD

**Issue by ayryq** [sblask/webextension-bookmark-dial#24]
### New Issue Checklist (tick off like this: `[x]`)

- [x ] I checked existing issues (open and closed) for possible duplicates
- [x ] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x ] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x ] Windows

### Description (please include examples/screenshots where applicable)
I'd like to be able to use this as the browser "home page" instead of just "new tab". I found an existing (closed) issue (#14 ) which referred to a beta version, apparently no longer available.

**Comment by sblask** [comment]
You can just manually set this up in the preferences. Choose custom URLs under Home and enter `moz-extension://e20a0fdd-664b-41bd-9463-3210fac6f8a8/content-scripts/bookmark-dial.html` (This is the URL I got when I right-clicked the bookmarkd dial and chose `Show page source`)
